trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: 'vs2017-win2016'

variables:
  configuration: 'Release'

steps:
  - template: common-steps.yaml
    parameters:
      buildConfiguration: $(configuration)

  - task: PublishBuildArtifacts@1
    displayName: "Upload dotnet Artifacts"
    inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'virtualconsult' 

  - task: PublishBuildArtifacts@1
    displayName: "Upload react Artifacts"
    inputs:
      pathtoPublish: 'Source/wwwroot/dist/'
      artifactName: 'virtualconsult-frontend'